apiVersion: skaffold/v1beta15
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: mur6/akka-cluster-test
      custom:
        buildCommand: sbt docker:publishLocal
        dependencies:
          paths:
            - ./src
            - ./build.sbt
deploy:
  kubectl:
    manifests:
      - ./k8s/akka-cluster-operator/deploy/*
      - ./k8s/akka-cluster.yaml
      # - ./k8s/akka-cluster2.yaml
portForward:
  - resourceType: deployment
    resourceName: akka-cluster-test
    port: 8080
    localPort: 9000
