apiVersion: app.lightbend.com/v1alpha1
kind: AkkaCluster
metadata:
  name: akka-cluster-test
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: main
          image: mur6/akka-cluster-test:latest
          readinessProbe:
            httpGet:
              path: "/ready"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
          livenessProbe:
            httpGet:
              path: "/alive"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
          ports:
            - name: http
              containerPort: 8080
            - name: remoting
              containerPort: 2552
            - name: management
              containerPort: 8558
