apiVersion: app.lightbend.com/v1alpha1
kind: AkkaCluster
metadata:
  name: akka-cluster-test
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: main
          image: mur6/akka-cluster-test:latest
          readinessProbe:
            httpGet:
              path: "/ready"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
          livenessProbe:
            httpGet:
              path: "/alive"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
          ports:
            - name: http
              containerPort: 8080
            - name: remoting
              containerPort: 2552
            - name: management
              containerPort: 8558
          # Add Linux Capabilities for to operate network routes
          # https://www.tsugihagi.net/entry/2014/10/05/083120
          # https://www.weave.works/blog/container-capabilities-kubernetes/
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
