apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: akka-cluster-test
  name: akka-cluster-test
spec:
  replicas: 5
  selector:
    matchLabels:
      app: akka-cluster-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: akka-cluster-test
        actorSystemName: akka-cluster-test
    spec:
      containers:
        - name: akka-cluster-test
          image: mur6/akka-cluster-test:latest
          imagePullPolicy: Never
          resources:
          livenessProbe:
            httpGet:
              path: /alive
              port: management
          readinessProbe:
            httpGet:
              path: /ready
              port: management
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            # akka remoting
            - name: remoting
              containerPort: 2552
              protocol: TCP
            # akka-management and bootstrap
            - name: management
              containerPort: 8558
              protocol: TCP
          # Add Linux Capabilities for to operate network routes
          # https://www.tsugihagi.net/entry/2014/10/05/083120
          # https://www.weave.works/blog/container-capabilities-kubernetes/
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
          env:
            # The Kubernetes API discovery will use this service name to look for
            # nodes with this value in the 'app' label.
            # This can be customized with the 'pod-label-selector' setting.
            - name: AKKA_CLUSTER_BOOTSTRAP_SERVICE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: "metadata.labels['app']"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
subjects:
  # Note the `name` line below. The first default refers to the namespace. The second refers to the service account name.
  # For instance, `name: system:serviceaccount:myns:default` would refer to the default service account in namespace `myns`
  - kind: User
    name: system:serviceaccount:default:default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
